data:
  path: "data/raw/telco_churn.csv"
  target_column: "Churn"

model:
  name: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1

training:
  random_state: 42
  test_size: 0.2
  trained_model_path: "models/random_forest_model.pkl"

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  artifact_root: "file:./mlruns"
  experiment_name: "Telco-Churn-Experiments"

output:
  model_dir: "models/"

data_transform:
  pipeline:
    - name: impute_missing_values
      transformer: imputer
      params:
        strategy: mean
      columns:
        - TotalCharges

    - name: encode_categorical
      transformer: encoder
      params:
        encoding_type: onehot
      columns:
        - gender
        - Partner
        - Dependents
        - PhoneService
        - MultipleLines
        - InternetService
        - OnlineSecurity
        - OnlineBackup
        - DeviceProtection
        - TechSupport
        - StreamingTV
        - StreamingMovies
        - Contract
        - PaperlessBilling
        - PaymentMethod

    - name: scale_numeric
      transformer: scaler
      params:
        scaling_type: standard
      columns:
        - MonthlyCharges
        - tenure

    - name: encode_target
      transformer: encoder
      params:
        encoding_type: label
      columns:
        - Churn