data:
  path: "data/raw/telco_churn.csv"
  target_column: "Churn"

model:
  name: "logistic_regression"
  params:
    penalty: "l2"
    solver: "lbfgs"
    max_iter: 2000

training:
  test_size: 0.25
  random_state: 42

output:
  model_dir: "models/"
  trained_model_path: "models/logistic_regression_model.pkl"

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  artifact_root: "/app/mlruns"
  experiment_name: "Telco-Churn-Experiments"

data_transform:
  pipeline:
    - name: impute_missing_values
      transformer: imputer
      params:
        strategy: mean
      columns:
        - TotalCharges

    - name: encode_categorical
      transformer: encoder
      params:
        encoding_type: onehot
      columns:
        - gender
        - Partner
        - Dependents
        - PhoneService
        - MultipleLines
        - InternetService
        - OnlineSecurity
        - OnlineBackup
        - DeviceProtection
        - TechSupport
        - StreamingTV
        - StreamingMovies
        - Contract
        - PaperlessBilling
        - PaymentMethod

    - name: scale_numeric
      transformer: scaler
      params:
        scaling_type: standard
      columns:
        - MonthlyCharges
        - tenure

    - name: encode_target
      transformer: encoder
      params:
        encoding_type: label
      columns:
        - Churn