data:
  path: "data/processed/processed_data.csv"
  target_column: "Churn"  # Target column name

model:
  name: "logistic_regression"  # Model to use
  params:  # Model-specific hyperparameters
    penalty: "l2"
    solver: "lbfgs"
    max_iter: 1000

training:
  test_size: 0.2  # Proportion of data to use for testing
  random_state: 42  # Random seed for reproducibility

output:
  model_dir: "models/"  # Directory to save the trained model
