data_transform:
  pipeline:
    - name: impute_missing_values
      transformer: imputer
      params:
        strategy: mean
      columns:
        - TotalCharges

    - name: encode_categorical
      transformer: encoder
      params:
        encoding_type: onehot
      columns:
        - gender
        - Partner
        - Dependents
        - PhoneService
        - MultipleLines
        - InternetService
        - OnlineSecurity
        - OnlineBackup
        - DeviceProtection
        - TechSupport
        - StreamingTV
        - StreamingMovies
        - Contract
        - PaperlessBilling
        - PaymentMethod

    - name: scale_numeric
      transformer: scaler
      params:
        scaling_type: standard
      columns:
        - MonthlyCharges
        - tenure

output:
  model_dir: "models/"
  trained_model_path: "models/logistic_regression_model.pkl"
  predictions_path: "output/predictions.csv"
